### ISSUE TITLE
Single line sources configuration issue

### ISSUE THREAD

**Issue by ozonni** [SumoLogic/sumologic-collector-docker#42]
I use sumologic/collector:latest-syslog docker container with the following sources json configuration:

```json
{"api.version": "v1", "sources": [{"category": "staging/containers", "forceTimeZone": "false", "protocol": "TCP", "sourceType": "Syslog", "encoding": "UTF-8", "port": "514", "name": "syslog-collector-container-tcp"}, {"category": "staging/containers", "forceTimeZone": "false", "protocol": "UDP", "sourceType": "Syslog", "encoding": "UTF-8", "port": "514", "name": "syslog-collector-container-udp"}]}
```

I see in sumologic ui that collector is created but with empty sources. If i take the same configuration, but i format json so it's multiline, then everything is ok. 
I don't see a reason why valid single line json should not work.

Docker logs:

$ docker logs cb04275bc1a7
Running SumoLogic Collector...

Thanks.

**Comment by maimaisie** [comment]
Interesting find! Thanks @ozonni for reporting. We will investigate and provide a fix.

**Comment by maimaisie** [comment]
Hi @ozonni , it looks like the problem is your json has the wrong type for the field "port". When I tried to repro using both the one liner json and formatted version, I got the following error in the collector log:
```
2017-05-23 18:15:08,143 +0000 [WrapperSimpleAppMain] INFO  com.sumologic.scala.collector.auth.CollectorRegistrationManager - [main] Response code is 200 with warnings: List(Key: validation.fields.invalid, Message: Field 'port' contains a value of the wrong type. Please consult the Collector Management API documentation, Key: validation.fields.invalid, Message: Field 'port' contains a value of the wrong type. Please consult the Collector Management API documentation), errors: List()
``` 
(logs can be found at `/opt/SumoCollector/logs/collector.log`)

After removing the quotes around 514, I can successfully create the collector with the source. Any chance that you fixed the type after changing the json to multiline?
