### ISSUE TITLE
apparmor blocking ptrace access on ubuntu 14.04

### ISSUE THREAD

**Issue by phobologic** [SumoLogic/sumologic-collector-docker#6]
When running the sumologic syslog collector in docker 1.7 on ubuntu 14.04, we see this showing up in our logs quite often:

```
Jun 10 00:11:17 ip-10-128-16-138 kernel: [13039.073448] type=1400 audit(1433895077.399:337): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=8930 comm="java" requested_mask="trace" denied_mask="trace" peer="docker-default"
Jun 10 00:12:17 ip-10-128-16-138 kernel: [13099.074012] type=1400 audit(1433895137.401:338): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=8930 comm="java" requested_mask="trace" denied_mask="trace" peer="docker-default"
Jun 10 00:13:17 ip-10-128-16-138 kernel: [13159.074626] type=1400 audit(1433895197.402:339): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=8930 comm="java" requested_mask="trace" denied_mask="trace" peer="docker-default"
```

This led me to this issue in docker:

https://github.com/docker/docker/issues/7276

I'm not sure what sumologic is doing with ptrace.  Even with those errors we seem to be getting our sumologic logs just fine, but we plan to update the docker run command to escalate the permissions given to sumologic in order to quiet the logs down and give it the access it needs.

**Comment by raychaser** [comment]
ok. this had me totally stumped. but: I finally got a moment to reproduce this, and indeed I can reproduce. it does look like the Docker enforced AppArmor profile simply doesn't allow ptrace.

if the main driver is to get rid of the logging (the denied ptrace attempts don't seem to be causing functionality issues) then these two radical solutions work, but because of their obvious side effects I can't recommend them.

- run with `--security-opt apparmor:uncofined`
- run `--privileged`

a less crazy option is to copy `/etc/apparmor.d/docker` to `/etc/apparmor.d/docker-ptrace` and then edit the new file to set the profile name to `docker-ptrace`, and add `ptrace peer=@{profile_name},`. then restart apparmor. here's full file based on my Ubuntu 15.04's Docker 1.8.1 profile:

```
#include <tunables/global>

profile docker-ptrace flags=(attach_disconnected,mediate_deleted) {

  #include <abstractions/base>

  network,
  capability,
  file,
  umount,

  deny @{PROC}/sys/fs/** wklx,
  deny @{PROC}/fs/** wklx,
  deny @{PROC}/sysrq-trigger rwklx,
  deny @{PROC}/mem rwklx,
  deny @{PROC}/kmem rwklx,
  deny @{PROC}/kcore rwklx,
  deny @{PROC}/sys/kernel/[^s][^h][^m]* wklx,
  deny @{PROC}/sys/kernel/*/** wklx,

  deny mount,

  deny /sys/[^f]*/** wklx,
  deny /sys/f[^s]*/** wklx,
  deny /sys/fs/[^c]*/** wklx,
  deny /sys/fs/c[^g]*/** wklx,
  deny /sys/fs/cg[^r]*/** wklx,
  deny /sys/firmware/efi/efivars/** rwklx,
  deny /sys/kernel/security/** rwklx,

  ptrace peer=@{profile_name},
}
```

I have not been successful in determining why we trigger ptrace. various experiments with other Java VM based containers didn't show the same. I also tried to pin it on the Tanuki wrapper, but no such luck.

from the Docker issue linked above it seems PID 1 can actually inspect itself. this is easily reproducible:

```
docker run -it ubuntu /bin/sh -c "ps"
```

will trigger the deny log entry but

```
docker run -it ubuntu ps
```

will not. I am going to take a look now whether I can change our Dockerfile to have the JVM actually be PID 1 without the `sh` and the `wrapper` stuff in between.

**Comment by phobologic** [comment]
Thanks - removing the sh & wrapper stuff will likely help with other issues going forward, since the shell script doesn't call exec.  Thanks for looking into this!

**Comment by raychaser** [comment]
good news.

```
docker run -v /tmp/clogs:/tmp/clogs -d --name="sumo-logic-collector-file-pid1" sumologic/collector:latest-file-pid1 -s /etc/sumo-sources.json -n docker-file -i [access-id] -k [access-key]
```

consider this experimental. the Dockerfile, as can be seen includes the collector version tag in some paths. I am going to try to get the installer changed to make at least a symlink to the collector version with a predictable name.
